### PR TITLE
Add California counties

### PR DESCRIPTION
**Pull request by daguar**
This PR adds a game for California county names (idea put out there by @lippytak https://github.com/codeforamerica/project-ideas/issues/75 )

One issue that I'd love review of prior to merge — there appears to be a slight offset with the base tiles:

screen shot 2015-07-04 at 3 42 18 pm

I'm not sure why this would be — the same file aligns with the base tiles on CartoDB fine — and consider it fairly minor, but wanted to flag.

Other minor notes:
- I modeled the metadata file after the [Colorado counties file](https://github.com/codeforamerica/click_that_hood/blob/master/public/data/colorado-counties.metadata.json), since it seemed to be the closest analogue
- The data has been compressed to lower precision than the original using [Mapshaper](http://mapshaper.org/) to keep the file size low and performance okay

### CODE REVIEW

**Comment by daguar** [comment]
Fixed the screenshot above — this is one that actually shows the issue:
screen shot 2015-07-04 at 3 42 18 pm

It appears LA County also has this problem:

screen shot 2015-07-04 at 3 42 24 pm

Not sure what's up with it! I lean towards considering it a separate issue from this PR.

**Comment by daguar** [comment]
Oh, I forgot there's one other minor issue that I wanted to raise just an an FYI — San Francisco is such a small county that it's excluded from the game:

**Comment by daguar** [comment]
(fixed screenshot above)

**Comment by daguar** [comment]
Heya @mwichary, anything I need to do to get this merged? I know CI is failing, but that appears unrelated to this PR.

**Comment by mwichary** [comment]
Sorry, was busy… but we can't get it live if the vectors don't align with
the map. Perhaps a manual intervention is necessary (there are a few in the
code right now).

**Comment by daguar** [comment]
No worries! So, quite oddly, for some reason I'm no longer seeing the misalignment (neither in this PR nor in the LA County example noted above.)

Not quite sure what it could have been (a tile cache?) but this should be good to go now.

To review, you can either pull down the branch and view it locally, or view a branch deploy I've done here: http://click-that-hood-cacounties.herokuapp.com/california-counties

**Comment by mwichary** [comment]
This is live now at http://click-that-hood.com/california-counties.

I’m sorry for the delay! Crazy week. Also, this map is really fun to play!!!

**Comment by daguar** [comment]
Awesome, thanks! And no worries, I totally understand busy weeks!

**Pull request merged**
