### PR TITLE
Fixed a hard-coded use of '/' as path separator that caused app.js to fail on Windows

### PR DESCRIPTION
**Pull request by huttarl**

### CODE REVIEW

**Comment by huttarl** [comment]
I didn't mean for the Charlotte area towns to be part of this PR. But, I guess they are.

**Comment by k-nut** [comment]
I think the fix for running this on Windows is a very good one (:rocket:) but I think that the neighborhoods should be handled in a separate one. 

Would you rebase this pull request to only include that change or create a new one with just the first commit? It would make the discussion much easier if the two topics were separated into to PRs. 

Feel free to let me know if there is anything I could help you with in the process.

**Comment by huttarl** [comment]
I actually did submit the fix for Windows by itself as a pull request; I don't understand how the Charlotte neighborhoods got into the same PR. (And now the Middle Eastern countries too.) I clicked "New pull request" for the Charlotte neighborhoods, but apparently it stuck new changes into the old PR.

I'll try to rebase, but I'm out of my depth here.

**Comment by huttarl** [comment]
@k-nut How do I rebase the pull request? I guess that's something I can do via github, since I created the PR via github?

**Pull request closed without merging**
