### PR TITLE
Adding City of Sydney

### PR DESCRIPTION
**Pull request by nefshja**

### CODE REVIEW

**Comment by mwichary** [comment]
Thanks for doing this – but do you know why do Mascot, Eastlakes, Kensington, and Darling Point have such weird shapes…?

e.g. 
image

**Comment by nefshja** [comment]
My guess is that the weird shapes are the segments of those neighbourhoods
which are included in the City of Sydney's LGA boundary.

**Comment by techieshark** [comment]
Ah, right, hmm... @mwichary, to produce this we clipped a countrywide suburbs (neighborhoods) shapefile by the boundary for the city of Sydney, so the clipping process may have resulted in fragments (some suburbs/neighborhoods are partly in Sydney and partly outside it).

**Comment by techieshark** [comment]
OK looking at it more in QGIS... it appears that Kensington has just a sliver of overlap with the City of Sydney (see the dark section on the borders in the image below). We should just remove that element from the geojson file.

tmp kensington-overlap

**Comment by techieshark** [comment]
Ah, and yes I checked the other suburbs mentioned. Same problem, as illustrated here (the only shapes with borders are the sliver polygons formed by the intersection of the suburbs and Sydney.

barely-intersecting-suburbs-with-sydney

**Comment by techieshark** [comment]
One last one... 

I clipped the suburbs file by Sydney's boundary, then manually selected each polygon which was large enough to click. That gave me what appeared to be everything but then I took the inverse of that selection using the attribute table (resulting in a selection of suburbs too small to click -- sliver polygons). I saved those slivers as a new shapefile and modified the map so only those had a black border and all other layers were just fill. 

You can see the sliver polygons as black lines, and I've then added in all suburbs and selected the ones that created those slivers.

The named suburbs should be all the ones that need to be removed from the dataset.

all-sydney-sliver-suburbs

**Comment by mwichary** [comment]
I don’t know if you meant to send an updated file, but I just removed the four offending neighbourhoods and pushed it live. http://click-that-hood.com/sydney 

Please send any further changes if you see them. :·)

Thank you!!!

**Comment by techieshark** [comment]
Awesome, thanks @mwichary!

**Comment by nefshja** [comment]
Yeah awesome stuff! Thanks!

**Pull request merged**
